### ISSUE TITLE
Problem z działaniem

### ISSUE THREAD

**Issue by MlodY8838** [gbaranski/quizizz-cheat#12]
Witam,
są 2 problemy z działaniem skryptu. Pierwszy problem to całkowite nie działanie skryptu występujące w sposób losowy.
Z błędem "Uncaught SyntaxError: Invalid or unexpected token" Wtedy skrypt sie nie załącza.
Jest natomiast jeszcze jeden problem, z działaniem skryptu, jeśli uda się go załączyć skrypt pokazuje poprawne odpowiedzi, ale podczas próby wybrania odpowiedzi quizizz pokazuje, że odpowiedź jest błędna.

Pozdrawiam i czekam na info.

**Comment by gbaranski** [comment]
That's most likely because you've copied the code incorrectly, some chat apps encode URL by default and make from " %22, which causes string to be unterminated. Remember to copy directly this code(also can be found in [README](https://github.com/gbaranski/quizizz-cheat/blob/master/README.md)
```js
fetch("https://raw.githubusercontent.com/gbaranski/quizizz-cheat/master/dist/bundle.js")
.then((res) => res.text()
.then((t) => eval(t)))
```

Please read carefully the instructions, you **mustn't your name**, instead of that put name of someone else taking a part in quiz.
