### ISSUE TITLE
Include proper copyright notice

### ISSUE THREAD

**Issue by Im-Beast** [gbaranski/quizizz-cheat#7]
Add info to README that it uses method from https://github.com/AndyFilter  instead of one simple comment

**Comment by gbaranski** [comment]
Hello, since idea or approach to a problem itself is not licensed, there's no need to include copyright notice. Please read carefully [MIT license](https://opensource.org/licenses/MIT) before arguing about it. In addition GPLv3 and MIT licenses are compatible(only from MIT to GPLv3)<sub>[Source](https://www.gnu.org/licenses/license-list.html#Expat)</sub>.
